### PR TITLE
feat(pipe): add no info pipe

### PR DESCRIPTION
**Pull request by nomospace**
image

### CODE REVIEW

**Comment by wghglory** [comment]
Thanks so much for providing this pipe functionality @nomospace ! One concern comes to my mind is that whether this pipe is suitable for the project. I think this pipe is not that general as it depends on the user application's need. For example, in a Chinese environment, the developer needs to provide a translated string and then pass it to the pipe. They may write this code in html: `'somestring' | noInfo: theirTranslationMethod('no.string.key')`, making the pipe less useful due to the theirTranslationMethod function call. 

If I am a developer in that project, I probably will create a custom pipe just for the project, rather than using the pipe in clr-extension because it's not a general thing. Just my thought. Please let me know what you think. @KingMario If you have comments, welcome to share~!

**Comment by KingMario** [comment]
I'm fine with the new pipe, but I prefer providing default strings for `display.no.info.string`.

**Comment by nomospace** [comment]
For chinese enviornment, how about we provide a default translation of "display.no.info.string"(which haven't been done in MR)? They can use their own translation or just use ours as I mentioned.

**Comment by wghglory** [comment]
> For chinese enviornment, how about we provide a default translation of "display.no.info.string"(which haven't been done in MR)? They can use their own translation if they've already provided in the i18n files or just use ours as I mentioned.

The challenge lies in the uncertainty of the translated string the application developer will employ. To address this, rather than proposing a default string, we could recommend that developers create a custom pipe for their translations. This approach aligns with the project's overarching goal of providing a universal solution. Introducing a project-specific pipe may not be the most suitable option in this scenario.

**Pull request closed without merging**
